# Generated by Django 4.0.4 on 2022-06-02 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(default='', verbose_name='Описание')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('importance', models.BooleanField(default=True, verbose_name='Важность')),
                ('condition', models.CharField(choices=[('Активно', 'Активно'), ('Отложено', 'Отложено'), ('Выполнено', 'Выполнено')], max_length=50, verbose_name='Состояние')),
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 6, 3, 11, 10, 6, 457758), verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
    ]
